version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: p@ss#2o24!
      MONGO_INITDB_ROOT_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - ./setup/volumes:/data/db
      - ./setup/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  planetprobe:
    container_name: planetprobe
    build:
      context: .
      dockerfile: Dockerfile
    image: planet-probe:latest
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: seven-challenge
      SPRING_DATA_MONGODB_USERNAME: sevenmars-usr
      SPRING_DATA_MONGODB_PASSWORD: pr0be_Ch@lleng&2o24!
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: seven-challenge
    depends_on:
      - mongo
    ports:
      - "8080:8080"